PREP(moduleInit);
PREP(hasCivilianHeadgear);
PREP(hasCivilianGoggles);
PREP(hasCivilianUniform);
PREP(hasCivilianVest);
PREP(isCivilianVehicle);
PREP(isInsideCivilianVehicle);
PREP(ignoreNightVision);
PREP(checkDisguise);
